engines:
  editorconfig:
    enabled: true
  eslint:
    enabled: true
  markdownlint:
    enabled: true
  nodesecurity:
    enabled: true
  tslint:
    enabled: true
    config: tslint.json
ratings:
  paths:
    - .storybook/**
    - config/**
    - hermione/**
    - public/**
    - scripts/**
    - server/**
    - src/**
    - tests/**
    - utils/**